services:
  # front:
  #   networks:
  #     - diflen
  back:
    build: ./backend/
    restart: always
    depends_on:
      - db
    env_file:
      - ./backend/.env
    networks:
      - diflen
  db:
    image: postgres:14-alpine
    restart: always
    env_file:
      - ./db/.env
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - diflen
  net:
    image: wbitt/network-multitool:extra
    networks:
      - diflen
  nginx:
    image: nginx
    restart: always
    networks:
      - diflen
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - db
      - back
    

networks:
  diflen:
volumes:
  db:
