services:
  # front:
  #   networks:
  #     - diflen
  back:
    build: ./backend/
    env_file:
      - .env
    networks:
      - diflen
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: diflen
      POSTGRES_USER: gab
      POSTGRES_PASSWORD: 1243def
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - diflen
  net:
    image: wbitt/network-multitool:extra
    networks:
      - diflen

networks:
  diflen:
volumes:
  db:
