services:
  # front:
  #   networks:
  #     - diflen
  back:
    build: ./backend/
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - db
    env_file:
      - ./backend/.env
    networks:
      - diflen
  db:
    image: postgres:14-alpine
    restart: always
    env_file:
      - ./db/.env
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - diflen
  net:
    image: wbitt/network-multitool:extra
    networks:
      - diflen

networks:
  diflen:
volumes:
  db:
